### ISSUE TITLE
数据有错误

### ISSUE THREAD

**Issue by casson** [fengyuanchen/distpicker#14]
441900: {
      441900: '三元里'
    },
    442000: {
      442000: '湖滨北路'
    },

东莞市，中山市，下面没有区县哦，另外我整理了一版mysql数据，正好能跟你这个配合上，有兴趣加我聊聊

**Comment by fengyuanchen** [comment]
目前中国共有五个不设市辖区的地级市，分别是东莞市、中山市、三沙市、儋州市、嘉峪关市。

**Comment by mkoplqq2006** [comment]
行政区划这块去年变化了很多，确实需要更新一下

**Comment by fengyuanchen** [comment]
地址数据已更新到2016年8月。
