### ISSUE TITLE
怎么根据value选择默认值  是value不是text

### ISSUE THREAD

**Issue by ivanmissu** [fengyuanchen/distpicker#15]
怎么根据value选择默认值  是value不是text

**Comment by fengyuanchen** [comment]
value === text

**Comment by dragonflylee** [comment]
大概楼上想问是怎么用data-code的值选择默认值，很多时候数据库存的是行政代码而不是省份名称

**Comment by realmx** [comment]
这代码是标准代码么？不是标准代码，那还是存名称吧，不然取出来对不上就不好了

**Comment by gewuxy** [comment]
同问，数据库存的应该是code才对

**Comment by fengyuanchen** [comment]
v2.0.0 已支持将ADCode（行政区划代码）设为value值。只需设置`valueType`配置项为`code`即可。

**Comment by fengyuanchen** [comment]
另外，ADCode也是经常变化的，比如一个地方从县级市升级为市区。所以建议还是直接在数据库中保存名字。
