### ISSUE TITLE
2.0 alpha 版的 placeholder 显示不出来

### ISSUE THREAD

**Issue by dekexu** [fengyuanchen/distpicker#17]
Custom placeholders

<div data-toggle="distpicker">
  <select data-province="---- 选择省 ----"></select>
  <select data-city="---- 选择市 ----"></select>
  <select data-district="---- 选择区 ----"></select>
</div>

这个地方应该显示为placeholder， 但是即使设置了，却还是一直显示为北京市跟北京市直辖区

**Comment by dekexu** [comment]
<div data-toggle="distpicker">
  <select data-province="---- 选择省 ----"></select>
  <select data-city="---- 选择市 ----"></select>
  <select data-district="---- 选择区 ----"></select>
</div>

**Comment by dekexu** [comment]
"<div data-toggle="distpicker">
  <select data-province="---- 选择省 ----"></select>
  <select data-city="---- 选择市 ----"></select>
  <select data-district="---- 选择区 ----"></select>
</div>"

**Comment by dekexu** [comment]
```html
<div data-toggle="distpicker">
  <select data-province="---- 选择省 ----"></select>
  <select data-city="---- 选择市 ----"></select>
  <select data-district="---- 选择区 ----"></select>
</div>

**Comment by fengyuanchen** [comment]
Got it. Thanks~

**Comment by dekexu** [comment]
OK 谢了， 看来还是得加js。

**Comment by fengyuanchen** [comment]
可以在HTML中配置：
```html
<div data-toggle="distpicker" data-auto-select="false">
  ...
</div>
```
