### ISSUE TITLE
东莞市下没有区

### ISSUE THREAD

**Issue by q326066766** [fengyuanchen/distpicker#22]
东莞市下没有区

**Comment by fengyuanchen** [comment]
东莞市下真没有区

**Comment by viliy** [comment]
东莞市下就没选项了

**Comment by suibobuzhuliu** [comment]
@fengyuanchen 请教下，行政区规划的数据是从哪里获取的？


[国家统计局行政区划代码](http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/)

这个更新也是挺慢的，这都马上17年了，才公布15年底的数据。

**Comment by rabbitns** [comment]
取值方法   重新赋值 方法都 没有啊？
