### ISSUE TITLE
在vue中使用了distpicker后，只有省显示出来，市显示不出来

### ISSUE THREAD

**Issue by NamelessChen** [fengyuanchen/distpicker#25]
在vue中使用了distpicker后，只有省显示出来，市显示不出来

**Comment by fengyuanchen** [comment]
是不是你自己代码的问题？

**Comment by Longx** [comment]
是的   我也遇到了这个问题，代码应该是没问题的

**Comment by SolidZORO** [comment]
这个的确是个问题，而且问题是不定时出现的，只要有 v-model 就会有机率出现。

所以涉及到 distpicker 的我目前还是用 js 去操作。
