### ISSUE TITLE
如何将distpicker作为module放入angular2中使用(或者说还不支持在angular2中使用)?

### ISSUE THREAD

**Issue by lzm420241** [fengyuanchen/distpicker#27]

**Comment by fengyuanchen** [comment]
```js
import 'distpicker';
```

**Comment by lzm420241** [comment]
以上写法在angular2 以js的方式是可行的,但是在ts中是无法通过编译的,第一个写法ng2无法识别module $,第二个语法都无法支持,另外使用jquery可通过declare var $:JQueryStatic, 而distpicker需要类似 import { module } from 'distpicker'的方式可通过编译,关键是我无法知道module在distpicker里面是什么
