### ISSUE TITLE
请问getDistricts为什么不能返回数据？

### ISSUE THREAD

**Issue by yokingma** [fengyuanchen/distpicker#30]
如图所示：
![qq 20161213001219](https://cloud.githubusercontent.com/assets/8767820/21106381/dc011802-c0c8-11e6-9e2b-5d5f64aa2132.jpg)

感谢作者提供这个好东西。

**Comment by fengyuanchen** [comment]
你实例化了吗？

**Comment by zsf513** [comment]
> 你实例化了吗？

$('#target').distpicker('getDistricts',331100);
