### ISSUE TITLE
不兼容IE8了?

### ISSUE THREAD

**Issue by chichumeng** [fengyuanchen/distpicker#32]
不兼容IE8了?

**Comment by fengyuanchen** [comment]
如果使用jQuery 1.x，应该是兼容的

**Comment by chichumeng** [comment]
用的是jQuery 1.x

distpicker 版本从2.x 之后测试,就已经不兼容 IE8了.

**Comment by fengyuanchen** [comment]
好吧，不过现在的主流网站都不再兼容IE8了。

**Comment by xasn** [comment]
求IE8解决方案，现在主流系统是win7，系统默认浏览器是IE8，IE8下报错：对象不支持此操作，4503行。

**Comment by fengyuanchen** [comment]
Version 2.x 已不在支持IE8。
