### ISSUE TITLE
亲 你这个在低版本avalonjs环境下跑不起来

### ISSUE THREAD

**Issue by vividxuan** [fengyuanchen/distpicker#34]
熬了个熬，亲可以看看是不是
https://cdnjs.cloudflare.com/ajax/libs/avalon.js/1.5.9/avalon.min.js这个不行
＝＝＝＝＝＝＝＝＝＝＝＝
https://cdnjs.cloudflare.com/ajax/libs/avalon.js/2.2.0/avalon.min.js这个可以
应该是低版本的amd作怪。。。

**Comment by fengyuanchen** [comment]
亲，这是一个jQuery插件啦。
