### ISSUE TITLE
与vue的冲突

### ISSUE THREAD

**Issue by Longx** [fengyuanchen/distpicker#35]
使用vue，通过v-model绑定数据，为什么只能显示省级栏，而市级和区级下面就没数据了 求作者帮助下！

**Comment by fengyuanchen** [comment]
你确定是Distpicker与Vue的冲突，而不是你自己没用对？

**Comment by Longx** [comment]
你可以自己尝试一下，把data-province初始化的信息用vue里的v-model双向绑定一下数据，会发现初始化的数据渲染不出来，但数据的确是双向绑定了！不使用vue的情况下能正常渲染出来。

**Comment by Longx** [comment]
而且当我不给data-province等值，我这边默认选中的是北京市、市辖区，而不是'——省——'这些个默认值了

**Comment by icehan2016** [comment]
请问这个问题解决了么？我也出现了相同的状况

**Comment by icehan2016** [comment]
我最终是这样解决的

`                userInfo:function(){                    //用户信息
                    this.$http.get(this.paths.infoUrl).then((response)=>{
                        this.user_data = response.body.user
                        $("#city").distpicker('destroy');
                        $("#city").distpicker({
                          province: this.user_data.info.province,
                          city: this.user_data.info.city
                        });
                    })
                },`

`                            <li id="city" data-toggle="distpicker">
                              <span>所在城市：</span>
                              <select data-province="" v-model='user_data.info.province'></select>
                              <select data-city=""     v-model='user_data.info.city' style="margin-left: 15px;"></select>
                            </li>`

**Comment by Longx** [comment]
你好，首先非常感谢帮我解答了这个问题，困扰了我许久。但我还有个小问题向你请教一下，为什么data-city要先给空值？而且还有个问题，当你user_data.info.city为空值时，我这边默认选中的是北京市了  应该是----省----才对。

**Comment by Longx** [comment]
<div data-toggle="distpicker"><select id="shop_pro" class="tag-main-input input-length" :data-province="filterInfo.filtProvince" v-model="filterInfo.filtProvince"></select><select id="shop_city" class="tag-main-input input-length" :data-city="filterInfo.filtCity" v-model="filterInfo.filtCity"></select>
</div>
我这边开始是这样解决的，但是缓存很严重，而且没值时，显示的也是北京市

**Comment by Longx** [comment]
<div data-toggle="distpicker">
								<select id="shop_pro" class="tag-main-input input-length" :data-province="filterInfo.filtProvince" v-model="filterInfo.filtProvince">
								</select>
								<select id="shop_city" class="tag-main-input input-length" :data-city="filterInfo.filtCity" v-model="filterInfo.filtCity"></select>
							</div>

**Comment by Longx** [comment]
<div data-toggle="distpicker">
								<select id="shop_pro" class="tag-main-input input-length" :data-province="filterInfo.filtProvince" v-model="filterInfo.filtProvince">
								</select>
								<select id="shop_city" class="tag-main-input input-length" :data-city="filterInfo.filtCity" v-model="filterInfo.filtCity"></select>
							</div>

**Comment by Longx** [comment]
<code>
   <div data-toggle="distpicker">
								<select id="shop_pro" class="tag-main-input input-length" :data-province="filterInfo.filtProvince" v-model="filterInfo.filtProvince">
								</select>
								<select id="shop_city" class="tag-main-input input-length" :data-city="filterInfo.filtCity" v-model="filterInfo.filtCity"></select>
							</div>
</code>
