### ISSUE TITLE
getDistricts 不能根据code获取name

### ISSUE THREAD

**Issue by fengzhongsen** [fengyuanchen/distpicker#36]
$().distpicker('getDistricts'); // 中国
$().distpicker('getDistricts', 330000); // 浙江省
$().distpicker('getDistricts', 330100); // 杭州市

不能根据code获取name

**Comment by fengyuanchen** [comment]
首先，`getDistricts`: 请注意这个方法里面的"Districts"是复数。
其次，`$().distpicker('getDistricts', 330100)[330106]; // 西湖区`。

**Comment by bossikill** [comment]
额 我也搞不出来..
