### ISSUE TITLE
下拉框无法默认显示‘选择省/市’的内容，总是默认选择第一个

### ISSUE THREAD

**Issue by niuguoqin** [fengyuanchen/distpicker#38]
如果想按照我标题中描述的那样显示，我该注意哪些地方呢？

**Comment by niuguoqin** [comment]
![dp2](https://cloud.githubusercontent.com/assets/13673478/26243043/170bc7d8-3cbd-11e7-8fd9-f10f895dbf8d.png)
![dp1](https://cloud.githubusercontent.com/assets/13673478/26243053/19d5680c-3cbd-11e7-8703-e10c5334a07e.png)
`Distpicker.DEFAULTS = {
    placeholder: true,
    province: '---- 选择省 ----',
    city: '---- 选择市 ----',
    district: '---- 选择区 ----'
  };`
`<p data-toggle="distpicker" style="width: 50%; float: left;">所在地区：
							<select id="selectProvince" name="province" data-province="---- 选择省 ----"></select>
							-
							<select id="selectCity" name="city" data-city="---- 选择市 ----"></select>
						</p>`
data-autoselect="0"也设置过，怎么都不行，我该怎么做呢？

**Comment by fengyuanchen** [comment]
不是有很多示例吗？！

> https://fengyuanchen.github.io/distpicker/
