### ISSUE TITLE
省市区不能数字转中文

### ISSUE THREAD

**Issue by bossikill** [fengyuanchen/distpicker#41]
$().distpicker('getDistricts'); // 中国
$().distpicker('getDistricts', 330000); // 浙江省
$().distpicker('getDistricts', 330100); // 杭州市

返回一个对象 不是 字符串

没效果...

把代码里面这行删掉
this.each(function each() {
/*里面的内容保留*/
});

然后就可以了
$().distpicker('getDistricts')['330000']
"浙江省"
$().distpicker('getDistricts',330000)[330100]
"杭州市"
$().distpicker('getDistricts',330100)['330102']
"上城区"

解决..

我不懂JS瞎改的 大佬看看是不是这个意思...

**Comment by fengyuanchen** [comment]
重新测试了一下，没毛病。是不是你没用对？
