### ISSUE TITLE
四个直辖市的郊县全部到市辖区里面了

### ISSUE THREAD

**Issue by iamziyue** [fengyuanchen/distpicker#5]
选择郊县为空，只有选择市辖区才包含所有区县。

**Comment by ganhb** [comment]
我在普通浏览器上正常使用，但放在微信公众号上城市跟县市的值获取不了，只能获取到省级的，控制台报出警告：Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

**Comment by sandmanman** [comment]
也发现了
我是手动把数据弄了下

**Comment by leiqiao0** [comment]
谢谢 @fengyuanchen，这个插件太方便了。

**Comment by Longx** [comment]
使用vue，通过v-model绑定数据，为什么只能显示省级栏，而市级和区级下面就没数据了  求作者帮助下！
