### ISSUE TITLE
加上 data-value-type="code" 之后显示不正常

### ISSUE THREAD

**Issue by blue0121** [fengyuanchen/distpicker#59]
<img width="644" alt="default" src="https://user-images.githubusercontent.com/21697764/42206979-4eef6252-7edb-11e8-8b19-f7f63117e697.png">
第一个option显示错误，而<option ...>广东省</option>没有加上selected

**Comment by fengyuanchen** [comment]
既然 valueType 为 code，那么 `data-province="广东省"` 就应该改成 `data-province="440000"`。

**Comment by fengyuanchen** [comment]
我还是做一下两者的兼容吧。
