### ISSUE TITLE
how to use its data in my own defined select tag?

### ISSUE THREAD

**Issue by xuuexu** [fengyuanchen/distpicker#61]
Hi, Mr. Chen.
Sorry for taking your time, I've for sure already read through the doc & issues;/
But it seems there is no clear answer for it.  

The original three select tags have many conflict with my bootstrap layout.
Any solution for this problem? like adding some class names?

<img width="576" alt="screen shot 2018-08-27 at 09 26 52" src="https://user-images.githubusercontent.com/31076337/44635963-8c34c280-a9db-11e8-89e1-34cd60d11bd3.png">

Here's my code snippet

**Comment by fengyuanchen** [comment]
Just apply this plugin on the parent element which contains all the select elements, and then the plugin will search the children tree to find out these select elements.
