### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by wot48** [fengyuanchen/distpicker#8]
distpicker always skip placeholder "---- 选择省 ----" and 
shows the next item on the list "北京“ by default.

**Comment by fengyuanchen** [comment]
Do you follow the API guide?

**Comment by wot48** [comment]
I read the instruction, maybe you can point me in the right direction.
I put the code on jsfiddle -> https://jsfiddle.net/jnsxbtnq

Thanks for making the plugin.

**Comment by fengyuanchen** [comment]
Done. Please check the changes: https://jsfiddle.net/jnsxbtnq/1/
